version: '3'

services:
  app:
    image: nikoheikkila/golang-docker-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-api
    env_file: .env
    restart: unless-stopped
    ports:
      - '${PORT:-3000}:3000'